// "regNumber":"M00982",/////// generated by the system
// "firstName":"gabttty",
// "lastName":"sunday1234",
// "email":"adeniranbayogold9001@gmail.com",
// "password":"123456789",
// "phoneNumber":"08129959272",
// "dateOfBirth":"2001-02-19T00:00:00.000Z",
// "gender":"male",
// "address":{
//     "street":"Ilorin",
//     "city":"Ilorin",
//     "state":"Ilorin"
// },
// "emergencyContact":{
//     "fullName":"Adeniran Gold",
//     "phoneNumber":"08129959272",
//     "relationship":"sibling"
//

import React from "react";

const signUpPage = () => {
  return <div>signUpPage</div>;
};

export default signUpPage;
